# -*- coding: utf-8 -*-
"""IA Generativa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F2mey37subNb8YtKL8sl_iyM5n_XcXEH

## Construção de Pipeline RAG para IA Generativa com Databricks e Python

## 1. Configuração de Ambiente

Nesta etapa, realizamos a instalação e importação dos pacotes necessários para execução do pipeline.
O ambiente foi preparado de forma a garantir todas as dependências compatíveis para o processamento de dados e a operação dos modelos de IA.
"""

!pip install -q "numpy==1.25.2" databricks-langchain langchain_milvus langchain-huggingface sentence-transformers beautifulsoup4

!pip install -q watermark

!pip install -q databricks-cli databricks-sql-connector

import os
os.environ["USER_AGENT"] = "LangChain (Google Colab)"

# Imports
import bs4
import sentence_transformers
from langchain_community.document_loaders import WebBaseLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.runnables import RunnablePassthrough
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from databricks_langchain import ChatDatabricks
from langchain_milvus import Milvus
import warnings
warnings.filterwarnings('ignore')

print("Ambiente Colab funcionando com sucesso.")

"""## 2. Configuração de Credenciais de Acesso

Nesta etapa, são definidas as credenciais de autenticação necessárias para conexão segura com o ambiente Databricks, garantindo acesso autorizado aos recursos da plataforma.

"""

# Defina as credenciais do Databricks
os.environ["DATABRICKS_HOST"] = "https://dbc-baba4cbd-2594.cloud.databricks.com/"   # Substitua pela URL do seu Databricks
os.environ["DATABRICKS_TOKEN"] = "DATABRICKS_TOKEN"           # Substitua pelo token gerado

"""## 3. Extração de Dados da Web e Criação de Chunks

Realiza-se a extração dos dados a partir da fonte web definida. Em seguida, o conteúdo bruto é segmentado em pequenos blocos (chunks) de texto, otimizando o processamento e a geração de embeddings para consultas posteriores.

"""

# Cria o carregador de dados da web
loader = WebBaseLoader("https://mitsloanreview.com.br/tecnologia/")

# Executa o carregador e extrai os dados da web
documentos = loader.load()

# Cria o separador de texto
text_splitter = RecursiveCharacterTextSplitter(chunk_size = 1800, chunk_overlap = 200)

# Aplica o separador e cria os chunks (documentos)
docs = text_splitter.split_documents(documentos)

len(docs)

"""## 4. Carregamento do Modelo de Embeddings

Inicializa-se o modelo de embeddings pré-treinado, que transforma os blocos de texto em vetores numéricos. Essa etapa é fundamental para permitir buscas semânticas no banco vetorial.

https://huggingface.co/BAAI/bge-small-en-v1.5
"""

# Carrega o modelo de embeddings
embeddings = HuggingFaceEmbeddings(model_name = "BAAI/bge-small-en-v1.5")

"""## 5. Criação e Carregamento do Banco de Dados Vetorial

Configura-se o banco de dados vetorial, responsável por armazenar e indexar os embeddings gerados. Essa estrutura viabiliza a recuperação eficiente dos dados relevantes para a geração de respostas.
"""

# Cria o banco de dados vetorial
vector_db = Milvus.from_documents(documents = docs,
                                      embedding = embeddings,
                                      collection_name = 'collection',
                                      index_params = {"index_type": "FLAT"},
                                      connection_args = {"uri": "./milvus.db"})

# Cria o retriever para recuperar os dados do Vector DB
retriever = vector_db.as_retriever()

retriever

# Testando o Retriever

# Define uma frase
query = "Quais são as tendências de tecnologia discutidas no blog?"

# Busca texto similar a frase dentro do banco vetorial
vector_db.similarity_search(query, k = 1)

"""## 6. Definindo o Endpoint do Modelo de Linguagem (LLM)

Nesta etapa, configuramos o endpoint do LLM hospedado no Databricks, que será utilizado para a geração das respostas a partir dos dados recuperados do banco vetorial.
"""

# Definimos aqui o endpoint para o LLM no Databricks
llm = ChatDatabricks(endpoint = "databricks-dbrx-instruct", max_tokens = 200)

"""## 7. Definindo o Prompt Template

Configuramos o template de prompt que orienta o modelo de linguagem na construção das respostas, garantindo consistência e direcionamento conforme o contexto dos dados extraídos.
"""

# Cria o texto do prompt
PROMPT_TEMPLATE = """
        Humano: Você é um assistente de IA e fornece respostas a perguntas do usuário.

        Use as seguintes informações para fornecer uma resposta concisa à pergunta entre as tags <question>.
        Se você não sabe a resposta, apenas diga que não sabe, não tente inventar uma resposta.

        <context>
        {context}
        </context>

        <question>
        {question}
        </question>

        A resposta deve ser específica e usar apenas informações confiáveis.

        Assistente:"""

# Cria o prompt template
prompt = PromptTemplate(template = PROMPT_TEMPLATE, input_variables = ["context", "question"])

# Cria o retriever
retriever = vector_db.as_retriever()

# Função para formatar os dados
def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

"""## 8. Definindo o RAG Chain para o Pipeline

Montamos a cadeia (chain) de componentes responsável por integrar a recuperação dos dados relevantes (Retrieval) e a geração de respostas (Generation) no pipeline RAG.
"""

# RAG Chain

rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

"""O `RunnablePassthrough` no LangChain é um componente que simplesmente encaminha os dados de entrada para a saída sem realizar alterações. Funciona como um "canal direto" de passagem. Neste projeto, utilizamos o `RunnablePassthrough` para transmitir a questão do usuário sem modificações até a próxima etapa do pipeline.

## 9. Executando o Pipeline

Com todos os componentes configurados, a execução do pipeline consiste em enviar uma pergunta, processá-la por meio da arquitetura RAG e retornar a resposta gerada com base nos documentos carregados.
"""

# Invoca a chain
resposta = rag_chain.invoke(query)

resposta

# Caixa de digitação para fazer perguntas
print("\n🔎 Pergunte algo sobre o conteúdo carregado:")
question = input("> Sua pergunta: ")

print("\n⏳ Gerando resposta...")
resposta = rag_chain.invoke(question)

print("\n📢 Resposta:\n")
for linha in resposta.split('\n'):
    print(linha)

"""# Fim"""